# "$PYTHON_ENV"/bin/python "./src/abstract_factory.py"
# "$PYTHON_ENV"/bin/python "./src/builder.py"
# "$PYTHON_ENV"/bin/python "./src/bridge.py"
# "$PYTHON_ENV"/bin/python "./src/composite.py"
# "$PYTHON_ENV"/bin/python "./src/decorator.py"
# "$PYTHON_ENV"/bin/python "./src/chain_of_responsability.py"
# "$PYTHON_ENV"/bin/python "./src/command.py"
# "$PYTHON_ENV"/bin/python "./src/mediator.py"
# "$PYTHON_ENV"/bin/python "./src/observer.py"
# "$PYTHON_ENV"/bin/python "./src/state_machine.py"
# "$PYTHON_ENV"/bin/python "./src/event_queue.py"
# "$PYTHON_ENV"/bin/python "./src/strategy.py"
# "$PYTHON_ENV"/bin/python "./src/template.py"
# "$PYTHON_ENV"/bin/python "./src/visitor.py"
# "$PYTHON_ENV"/bin/python "./src/singleton.py"
"$PYTHON_ENV"/bin/python "./src/borg.py"
